ACCESORIOS/urls.py
from django.urls import path
from ACCESORIOS import views

app_name = 'ACCESORIOS'

urlpatterns = [
    path('ruedas/', views.ListadoRuedas.as_view(), name='listado_ruedas'),
    path('ruedas/crear/', views.CrearRuedas.as_view(), name='crear_ruedas'),
    path('ruedas/<int:pk>/', views.VerRuedas.as_view(), name='ver_ruedas'),
    path('ruedas/<int:pk>/editar/', views.EditarRuedas.as_view(), name='editar_ruedas'),
    path('ruedas/<int:pk>/eliminar/', views.EliminarRuedas.as_view(), name='eliminar_ruedas'),
]

DERBYSTORE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('START.urls')),
    path('accesorios/', include('ACCESORIOS.urls')),
    path('usuarios/', include('usuarios.urls'))
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

START/urls.py
from django.urls import path
from START.views import (
    vista, 
    inicio, 
    template1,
    crear_patines, 
    about_me, 
    buscar_patines, 
    ver_patines, 
    eliminar_patines, 
    editar_patines)


urlpatterns = [
    path('vista/', vista, name='vista'),
    path('', inicio, name='inicio'),
    path('deportes/', template1, name='deportes'),
    path('crear-patines/<str:Deporte>/<str:Marca>/<int:Talla>/', crear_patines, name='crear_patines'),
    path('buscar-patines/', buscar_patines, name='buscar_patines'),
    path('crear-patines/', crear_patines, name='crear_patines'),
    path('ver-patines/<int:id>/', ver_patines, name='ver_patines'),
    path('eliminar-patines/<int:id>/', eliminar_patines, name='eliminar_patines'),
    path('editar-patines/<int:id>/', editar_patines, name='editar_patines'),
    path('about-me/', about_me, name='about_me')
]

ACCESORIOS/models.py
from django.db import models

class ruedas(models.Model):
    Dureza = models.CharField(max_length=4)
    Perfil = models.CharField(max_length=9)
    Compuesto = models.CharField(max_length=15)
    Talla = models.IntegerField()
    Anio = models.IntegerField(default=2024)
    Fecha_carga = models.DateField(default="2024-01-01")
    
    def __str__(self):
        return f'{self.id} {self.Dureza} {self.Perfil} {self.Anio}'

ACCESORIOS/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from ACCESORIOS.models import ruedas
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class CrearRuedas(CreateView):
    model = ruedas
    template_name = 'accesorios/crear_ruedas.html'
    success_url = reverse_lazy('ACCESORIOS:listado_ruedas')
    fields = ['Dureza', 'Perfil', 'Compuesto', 'Talla', 'Fecha_carga']
    
    
class ListadoRuedas(ListView):
    model = ruedas
    template_name = 'accesorios/listado_ruedas.html'
    context_object_name = 'ruedas'
    
    
class VerRuedas(LoginRequiredMixin, DetailView):
    model = ruedas
    template_name = 'accesorios/ver_ruedas.html'


class EditarRuedas(LoginRequiredMixin, UpdateView):
    model = ruedas
    template_name = "accesorios/editar_ruedas.html"
    success_url = reverse_lazy('ACCESORIOS:listado_ruedas')
    fields = ['Dureza', 'Perfil', 'Compuesto', 'Talla']
    
    
class EliminarRuedas(DeleteView):
    model = ruedas
    template_name = "accesorios/eliminar_ruedas.html"
    success_url = reverse_lazy('ACCESORIOS:listado_ruedas')
    

ACCESORIOS/templates/accesorios/crear_ruedas.html
{% extends "base.html" %}

{% block title_head %}
Crear Ruedas
{% endblock title_head %}

<!-- Vacía el contenido del masthead -->
{% block header %}{% endblock header %}
{% block main_uptext %}{% endblock main_uptext %}
{% block main_text %}{% endblock main_text %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}
{% block contact %}{% endblock contact %}

{% block main %}
<div class="mt-5">
    <li><h2 class="text-center">Crear Ruedas</h2>
    </li>
    <form action="{% url 'ACCESORIOS:crear_ruedas' %}" method="POST" class="mt-4">
        {% csrf_token %}

{{form}}
        <input type='submit' value='Agregar'>
    </form>    
{% endblock main %}

ACCESORIOS/templates/accesorios/editar_ruedas.html
{% extends "base.html" %}

{% block title_head %}
Editar Ruedas
{% endblock title_head %}

<!-- Vacía el contenido del masthead -->
{% block header %}{% endblock header %}
{% block main_uptext %}{% endblock main_uptext %}
{% block main_text %}{% endblock main_text %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}
{% block contact %}{% endblock contact %}

{% block main %}
<div class="mt-5">
    <li><h2 class="text-center">Editar Ruedas</h2>
    </li>
    <form action={% url 'ACCESORIOS:editar_ruedas' ruedas.id %} method="POST">
        {% csrf_token %}
{{form}}

        <input type='submit' value='Editar'>
    </form>    

{% endblock main %}

ACCESORIOS/templates/accesorios/eliminar_ruedas.html
{% extends "base.html" %}

{% block title_head %}
Eliminar Ruedas
{% endblock title_head %}

<!-- Vacía el contenido del masthead -->
{% block header %}{% endblock header %}
{% block main_uptext %}{% endblock main_uptext %}
{% block main_text %}{% endblock main_text %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}
{% block contact %}{% endblock contact %}
{% block h1_header %}Eliminar Ruedas{% endblock h1_header %}


{% block main %}
<div class="mt-5">
    <li><h2 class="text-center">Eliminar Ruedas</h2>
    </li>
    <form action={% url 'ACCESORIOS:eliminar_ruedas' ruedas.id %} method="POST">
        {% csrf_token %}
        <p>
        </p>
        
        <h3>
            <p>¿Desea eliminar las ruedas? {{ruedas}}?</p>
        </h3>

        <input type="submit" value="Confirmar">
</form>

{% endblock main %}

ACCESORIOS/templates/accesorios/listado_ruedas.html
{% extends "base.html" %}

{% block title_head %}
Listado de Ruedas
{% endblock title_head %}

<!-- Vacía el contenido del masthead -->
{% block header %}{% endblock header %}
{% block main_uptext %}{% endblock main_uptext %}
{% block main_text %}{% endblock main_text %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}
{% block contact %}{% endblock contact %}

{% block main %}
<div class="mt-5">
    <h2 class="text-center">Ruedas en inventario</h2>
    <p>
    </p>   
    <h2 class="text.center">
        <a href={% url 'ACCESORIOS:crear_ruedas' %}>Agregar modelo de Ruedas</a>
    </h2>
    

{% if ruedas %}
    <h3 class="mt-5">Resultados:</h3>
    <ul class="list-group">
        {% for rueda in ruedas %}
        <li class="list-group-item">
            {{ rueda }}
            | <a href="{% url 'ACCESORIOS:ver_ruedas' rueda.id %}">Ver más</a>
            | <a href="{% url 'ACCESORIOS:editar_ruedas' rueda.id %}">Editar</a>
            | <a href="{% url 'ACCESORIOS:eliminar_ruedas' rueda.id %}">Eliminar</a>
        </li>
{% endfor %}
    </ul>
    {% else %}
    <p class="mt-3 text-muted">No hay ruedas registradas.</p>
    {% endif %}
</div>
{% endblock main %}

ACCESORIOS/templates/accesorios/ver_ruedas.html
{% extends "base.html" %}

{% block title_head %}
Ver Ruedas
{% endblock title_head %}

<!-- Vacía el contenido del masthead -->
{% block header %}{% endblock header %}
{% block main_uptext %}{% endblock main_uptext %}
{% block main_text %}{% endblock main_text %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}
{% block contact %}{% endblock contact %}
{% block h1_header %}{{ruedas}}{% endblock h1_header %}


{% block main %}
<div class="mt-5">
    <li><h2 class="text-center">Ver Ruedas</h2>
    </li>
    <ul>
        <p><il>Dureza: {{ruedas.Dureza}}</il><p>
        <p><il>Perfil: {{ruedas.Perfil}}</il><p>
        <p><il>Compuesto: {{ruedas.Compuesto}}</il><p>
        <p><il>Talla: {{ruedas.Talla}}</il><p>
        <p><il>Fecha carga: {{ruedas.Fecha_carga}}</il><p>
    </ul>

<ul>
    <h4>| <a href= {% url 'ACCESORIOS:listado_ruedas' %}>Volver</a> | </h4>
</ul>{% endblock main %}