DERBYSTORE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('START.urls')),
    path('accesorios/', include('ACCESORIOS.urls')),
    path('usuarios/', include('usuarios.urls'))
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

START/urls.py
from django.urls import path
from START.views import (
    vista, 
    inicio, 
    template1,
    crear_patines, 
    about_me, 
    buscar_patines, 
    ver_patines, 
    eliminar_patines, 
    editar_patines)


urlpatterns = [
    path('vista/', vista, name='vista'),
    path('', inicio, name='inicio'),
    path('deportes/', template1, name='deportes'),
    path('crear-patines/<str:Deporte>/<str:Marca>/<int:Talla>/', crear_patines, name='crear_patines'),
    path('buscar-patines/', buscar_patines, name='buscar_patines'),
    path('crear-patines/', crear_patines, name='crear_patines'),
    path('ver-patines/<int:id>/', ver_patines, name='ver_patines'),
    path('eliminar-patines/<int:id>/', eliminar_patines, name='eliminar_patines'),
    path('editar-patines/<int:id>/', editar_patines, name='editar_patines'),
    path('about-me/', about_me, name='about_me')
]

usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView


app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/password/', views.CambiarPassword.as_view(), name='cambiar_password'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout')
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.utils import IntegrityError


class DatosExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares/', blank=True, null=True)
    

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField(max_length=500, blank=True, null=True)
    photo = models.ImageField(upload_to='user_photos/', blank=True, null=True)

    def __str__(self):
        return f"Perfil de {self.user.username}"


def get_or_create_profile(user):
    try:
        profile, created = UserProfile.objects.get_or_create(user=user)
        return profile
    except IntegrityError:
        
        return UserProfile.objects.filter(user=user).first()

User.add_to_class("get_or_create_profile", get_or_create_profile)

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from usuarios.models import DatosExtra, UserProfile


class FormularioDeCreacionDeUsuario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contrasenia', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir Contrasenia', widget=forms.PasswordInput)
    first_name = forms.CharField(label='Nombre')
    last_name = forms.CharField(label='Apellido')
    
    class Meta:
        model = User
        fields = ['username', 'email','first_name', 'last_name', 'password1', 'password2']
        help_texts = {key: '' for key in fields}

        
class FormularioEdicionPerfil(UserChangeForm):
    email = forms.EmailField(label='Correo electrónico')
    first_name = forms.CharField(label='Nombre')
    last_name = forms.CharField(label='Apellido')
    avatar = forms.ImageField(label='Avatar', required=False)
    password = None

    class Meta:
        model = DatosExtra
        fields = ['email', 'first_name', 'last_name', 'avatar']
        
        
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['photo', 'bio']

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth import authenticate, login as django_login
from usuarios.forms import FormularioDeCreacionDeUsuario, FormularioEdicionPerfil, UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from usuarios.models import DatosExtra, UserProfile
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash


def login(request):
    
    formulario = AuthenticationForm()
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.get_user()
            
            django_login(request, usuario)
            
            DatosExtra.objects.get_or_create(user=usuario)
            return redirect('inicio')
            
    return render(request, 'usuarios/login.html', {'form': formulario})


def register(request):
    
    formulario = FormularioDeCreacionDeUsuario()
    if request.method == 'POST':
        formulario = FormularioDeCreacionDeUsuario(request.POST)
        if formulario.is_valid():
            
            formulario.save()
            
            return redirect('usuarios:login')
    
    return render(request, 'usuarios/register.html', {'form': formulario})

@login_required
def editar_perfil(request):
    datos_extra = request.user.datosextra
    formulario = FormularioEdicionPerfil(instance=request.user, initial={'avatar': datos_extra.avatar})
    
    if request.method == 'POST':
        formulario = FormularioEdicionPerfil(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            
            new_avatar = formulario.cleaned_data.get('avatar')
            datos_extra.avatar = new_avatar if new_avatar else datos_extra.avatar
            datos_extra.save()
            
            formulario.save()
            return redirect('inicio')
    
    return render(request, 'usuarios/editar_perfil.html', {'form': formulario})


class CambiarPassword(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuarios/cambiar_password.html'
    success_url = reverse_lazy('usuarios:editar_perfil')  
    

@login_required
def profile(request):
    profile = request.user.get_or_create_profile()
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST, request.FILES, instance=request.user.profile)
        password_form = PasswordChangeForm(request.user, request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)  
            return redirect('usuarios:profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        password_form = PasswordChangeForm(request.user)
        
        return render(request, 'usuarios/profile.html', {
            'user_form': user_form,
            'profile_form': profile_form,
            'password_form': password_form
    })

    

usuarios/templates/usuarios/cambiar_password.html
{% extends 'base.html' %}

{% block title_head %}
Cambiar password
{% endblock title_head %}

{% block h1_header %}
Cambiar password de {{request.user.username}}
{% endblock h1_header %}

<!-- Vacía el contenido del masthead -->
{% block header %}{% endblock header %}
{% block main_uptext %}{% endblock main_uptext %}
{% block main_text %}{% endblock main_text %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}
{% block contact %}{% endblock contact %}

{% block main %}
<div class="mt-5">
    <li><h2 class="text-center">Cambiarás de Contraseña {{request.user.username}} </h2>
    </li>
    <form action={% url 'usuarios:cambiar_password' %} method='post'>
        {% csrf_token %}

{{form}}
        <input type='submit' value='Guardar cambios'>

</form>

{% endblock main %}

usuarios/templates/usuarios/editar_perfil.html
{% extends "base.html" %}

{% block title_head %}
Editar Perfil
{% endblock title_head %}


<!-- Vacía el contenido del masthead -->
{% block header %}{% endblock header %}
{% block main_uptext %}{% endblock main_uptext %}
{% block main_text %}{% endblock main_text %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}
{% block contact %}{% endblock contact %}


{% block main %}
<div class="mt-5">
    <li><h2 class="text-center">Editar Perfil de {{request.user.username}} </h2>
    </li>
    <form action={% url 'usuarios:editar_perfil' %} method='post' enctype='multipart/form-data'>
        {% csrf_token %}

        {{form}}
        <input type='submit' value='Editar'>

</form>
<p>
<h2><a href={% url 'usuarios:cambiar_password' %}>Cambiar password</a><h2>
</p>

    <a href="{% url 'usuarios:profile' %}">Ver mi perfil</a>
{% endblock main %}

usuarios/templates/usuarios/login.html
{% extends 'base.html' %}

{% block title_head %}
Inicio de sesión
{% endblock title_head %}
{% block main_uptext %}{% endblock main_uptext %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}

{% block main %}

<form action={% url 'usuarios:login' %} method='post'>
    {% csrf_token %}

    {{form}}
    <input type='submit' value='Iniciar sesion'>

</form>

{% endblock main %}

usuarios/templates/usuarios/logout.html
{% extends "base.html" %}

{% block title_head %}
Cerrar sesión
{% endblock title_head %}

<!-- Vacía el contenido del masthead -->
{% block main_uptext %}{% endblock main_uptext %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}


{% block main %}

<div class="mt-5">
    <p>
    <h1 class="text-center">Cerraste sesión correctamente.</h1>
<ul>
    <h4>| <a href= {% url 'inicio' %}>Inicio</a> | </h4>
</ul>  
    </p>
{% endblock main %}

usuarios/templates/usuarios/profile.html
{% extends 'base.html' %}

<!-- Vacía el contenido innecesario -->
{% block header %}{% endblock %}
{% block main_uptext %}{% endblock %}
{% block main_text %}{% endblock %}
{% block categorias %}{% endblock %}
{% block vista_about %}{% endblock %}
{% block contact %}{% endblock %}

{% block main %}
<div class="mt-5">
    <h2 class="text-center">Perfil de {{ user.username }}</h2>

    <h3 class="mt-5">Información del perfil:</h3>
    <p><strong>Nombre:</strong> {{ user.first_name }}</p>
    <p><strong>Apellido:</strong> {{ user.last_name }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>

    <p><strong>Biografía:</strong> {{ user.profile.bio }}</p>
    <p><strong>Foto:</strong></p>
    {% if user.profile.photo %}
        <img src="{{ user.profile.photo.url }}" alt="Foto de {{ user.username }}" style="max-width: 200px;">
    {% else %}
        <p>No se ha subido una foto de perfil.</p>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="border p-3">
            <legend>Editar información personal</legend>
            {{ user_form.as_p }}
        </fieldset>

        <fieldset class="border p-3 mt-4">
            <legend>Subir foto de perfil</legend>
            {{ profile_form.as_p }}
        </fieldset>

        <fieldset class="border p-3 mt-4">
            <legend>Cambiar contraseña</legend>
            {{ password_form.as_p }}
        </fieldset>
        <div class="text-center mt-4">
            <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </div>
    </form>




</div>
{% endblock %}

usuarios/templates/usuarios/register.html
{% extends "base.html" %}

{% block title_head %}
Registro
{% endblock title_head %}

<!-- Vacía el contenido del masthead -->
{% block main_uptext %}{% endblock main_uptext %}
{% block categorias %}{% endblock categorias %}
{% block vista_about %}{% endblock vista_about %}

{% block main %}
<p>
</p> 
<div class="mt-5">
    <h2 class="text-center">Registro</h2>
    <form action={% url 'usuarios:register' %} method='post' class="mt-5">
    {% csrf_token %}

    {{form}}
    <input type='submit' value='Registrarse'>

</form>
</div>
{% endblock main %}